version: 2
jobs:
  build:
    docker:
      - image: maven:3.6.2-jdk-11
    steps:
      - checkout
      - run:
          name: Build
          command: |
            mvn clean
            mvn package
      - run:
          name: Deployment
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              chmod 400 your_private_key.pem
              ssh -i "your_private_key.pem" ec2-user@your_public_dns.compute.amazonaws.com
            fi
workflows:
  version: 2
  build_and_push:
    jobs:
      - build
